default_shell:
    - user: 'vagrant'
      shell: '/bin/zsh'

basic_pkgs:
    - zip
    - curl
    - zsh
    - git
    - mc
    - python-pycurl
    - python-software-properties
#    - openjdk-7-jre-headless
