php_pkgs:
  - php5-mysql
  - php5-curl
  - php5-gd
  - php5-intl
  - php-pear
  - php5-imagick
  - php5-imap
  - php5-mcrypt
  - php5-memcache
  - php5-ming
  - php5-ps
  - php5-pspell
  - php5-recode
  - php5-snmp
  - php5-sqlite
  - php5-tidy
  - php5-xmlrpc
  - php5-xsl
  - php5-xdebug

config_files:
    - src: 'vagrant.conf.j2'
      dest: '/etc/apache2/sites-available/010-vagrant.conf'
      owner: 'vagrant'
      group: 'vagrant'
      mode: '0644'
    - src: 'opcache.ini.j2'
      dest: '/etc/php5/mods-available/opcache.ini'
      owner: 'vagrant'
      group: 'vagrant'
      mode: '0644'
    - src: 'xdebug.ini.j2'
      dest: '/etc/php5/mods-available/xdebug.ini'
      owner: 'vagrant'
      group: 'vagrant'
      mode: '0644'
    - src: 'etc-php5-apache2-php.ini.j2'
      dest: '/etc/php5/apache2/php.ini'
      owner: 'vagrant'
      group: 'vagrant'
      mode: '0644'

config_files_54:
    - src: 'vagrant.conf.54.j2'
      dest: '/etc/apache2/sites-available/vagrant'
      owner: 'vagrant'
      group: 'vagrant'
      mode: '0644'
    - src: 'xdebug.ini.54.j2'
      dest: '/etc/php5/mods-available/xdebug.ini'
      owner: 'vagrant'
      group: 'vagrant'
      mode: '0644'
    - src: 'etc-php5-apache2-php.ini.j2'
      dest: '/etc/php5/apache2/php.ini'
      owner: 'vagrant'
      group: 'vagrant'
      mode: '0644'

# php.ini
php_max_execution_time: '90'
php_display_errors: 'On'
php_display_startup_errors: 'On'
php_html_errors: 'Off'
php_post_max_size: '32M'
php_upload_max_filesize: '32M'
php_date_timezone: 'Europe/Berlin'

# my.cnf
mysql_max_allowed_packet: '128M'
mysql_character_set_server: 'utf8'
mysql_collation_server: 'utf8_general_ci'
innodb_file_per_table: 'innodb_file_per_table'

# mysql
mysql_root_password: 'n<_665{vS43y'


#phpunit - pear dependencies
pear_deps:
  - cmd: 'channel-discover pear.phpunit.de'
  - cmd: 'channel-discover components.ez.no'
  - cmd: 'channel-discover pear.symfony.com'
  - cmd: 'install --alldeps phpunit/PHPunit'