
- name: Anlegen Mysql User für ddctp
  mysql_user: name='testmartin' password='testpasswort' priv=*.*:ALL state=present
  tags: mysql

- name: Datenbanken für ddctp anlegen
  mysql_db: name='testaufgabe' state=present
  tags: mysql

- name: SQL Files hochladen
  copy: src=db.sql  dest=/tmp/db.sql owner=vagrant
  with_items: ${dbs}
  tags: mysql

- name: SQL Files einspielen
  shell: mysql --host=localhost --user=testmartin --password=testpasswort testaufgabe < /tmp/db.sql
  with_items: ${dbs}
  tags: mysql