- include: php55.yml

- name: PhpUnit
  copy: src=phpunit.phar dest=/usr/local/bin/phpunit.phar
  register: result

- command: chmod +x /usr/local/bin/phpunit.phar

- file: src=/usr/local/bin/phpunit.phar dest=/usr/local/bin/phpunit owner=vagrant group=vagrant state=link

- debug: var=result

- name: Enable Mod-Rewrite
  command: a2enmod rewrite

- name: MySQL | Configuration file, my.cnf
  template: src=etc-mysql-my.cnf.j2 dest=/etc/mysql/my.cnf
  tags: db

- include: mysql-secure.yml

- include: application.yml

- name: Restart Apache
  service: name=apache2 state=restarted

- name: Restart MySQL
  service: name=mysql state=restarted
  tags: db

- name: Gruppe www-data für Vagrant
  sudo: True
  shell: adduser vagrant www-data

- name: Gruppe vagrant für www-data
  sudo: True
  shell: adduser www-data vagrant
