- name: Repository last Php5
  apt_repository: repo='ppa:ondrej/php5' update_cache=yes

- debug: var=ansible_hostname

- name: Install Apache2, Php and Mysql
  apt: pkg={{item}} state=installed
  with_items:
  - apache2
  - php5
  - libapache2-mod-php5
  - mysql-server
  - mysql-client
  - python-mysqldb

- name: Install Php Modules
  apt: pkg={{item}} state=installed
  with_items: php_pkgs
  tags: php-pkgs

- name: Write config files
  sudo: True
  template: src={{item.src}} dest={{item.dest}} owner={{item.owner}} group={{item.group}} mode={{item.mode}}
  with_items: config_files
  tags: config-files

- name: Enable Site Vagrant
  command: a2ensite 010-vagrant.conf

- name: Disable Default Site
  command: a2dissite 000-default.conf

- lineinfile: dest=/etc/hosts state=present line="127.0.0.1       test.localhost"